# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 574)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background=rgb(255, 170, 0)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 764))
        self.centralwidget.setStyleSheet("QMainWindow{\n"
"background=rgb(255, 170, 0)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(1, 1, 800, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QMainWindow{\n"
"background=rgb(255, 170, 0)\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setStyleSheet("QWidget {\n"
"background:#4fc3f7\n"
"}")
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 791, 521))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 1, 1, 1)
        self.installmentsPeriod = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.installmentsPeriod.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.installmentsPeriod.setMaximum(999999)
        self.installmentsPeriod.setProperty("value", 10)
        self.installmentsPeriod.setObjectName("installmentsPeriod")
        self.gridLayout_3.addWidget(self.installmentsPeriod, 1, 0, 1, 1)
        self.installmentsSum = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.installmentsSum.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.installmentsSum.setMaximum(999999999)
        self.installmentsSum.setSingleStep(1000)
        self.installmentsSum.setProperty("value", 10000)
        self.installmentsSum.setObjectName("installmentsSum")
        self.gridLayout_3.addWidget(self.installmentsSum, 0, 0, 1, 1)
        self.ResultLabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.ResultLabel_3.setText("")
        self.ResultLabel_3.setObjectName("ResultLabel_3")
        self.gridLayout_3.addWidget(self.ResultLabel_3, 4, 0, 1, 1)
        self.installmentsCalcButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installmentsCalcButton.sizePolicy().hasHeightForWidth())
        self.installmentsCalcButton.setSizePolicy(sizePolicy)
        self.installmentsCalcButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.installmentsCalcButton.setStyleSheet("QPushButton {\n"
"background:#b3e5fc;\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"\n"
"}\n"
"")
        self.installmentsCalcButton.setObjectName("installmentsCalcButton")
        self.gridLayout_3.addWidget(self.installmentsCalcButton, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setMinimumSize(QtCore.QSize(300, 0))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 1, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_3)
        self.plainTextEdit_3.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_3.addWidget(self.plainTextEdit_3, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setStyleSheet("QWidget {\n"
"background:#ac68cc\n"
"}")
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        self.loanInterestRate = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.loanInterestRate.setStyleSheet("QWidget {\n"
"background:#d6b4e7\n"
"}")
        self.loanInterestRate.setSingleStep(0.1)
        self.loanInterestRate.setProperty("value", 10.0)
        self.loanInterestRate.setObjectName("loanInterestRate")
        self.gridLayout_2.addWidget(self.loanInterestRate, 1, 0, 1, 1)
        self.loanPeriod = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.loanPeriod.setStyleSheet("QWidget {\n"
"background:#d6b4e7\n"
"}")
        self.loanPeriod.setMaximum(999999)
        self.loanPeriod.setProperty("value", 10)
        self.loanPeriod.setObjectName("loanPeriod")
        self.gridLayout_2.addWidget(self.loanPeriod, 2, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_2.addWidget(self.radioButton_3, 3, 1, 1, 1)
        self.loanCalcButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loanCalcButton.sizePolicy().hasHeightForWidth())
        self.loanCalcButton.setSizePolicy(sizePolicy)
        self.loanCalcButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loanCalcButton.setStyleSheet("QPushButton {\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"background:#d6b4e7\n"
"}")
        self.loanCalcButton.setObjectName("loanCalcButton")
        self.gridLayout_2.addWidget(self.loanCalcButton, 4, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 3, 0, 1, 1)
        self.ResultLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ResultLabel_2.setText("")
        self.ResultLabel_2.setObjectName("ResultLabel_2")
        self.gridLayout_2.addWidget(self.ResultLabel_2, 6, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEdit_2.setStyleSheet("QWidget {\n"
"background:#d6b4e7\n"
"}")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_2.addWidget(self.plainTextEdit_2, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(300, 0))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 1, 1, 1)
        self.loanSum = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.loanSum.setStyleSheet("QWidget {\n"
"background:#d6b4e7\n"
"}")
        self.loanSum.setMaximum(999999999)
        self.loanSum.setSingleStep(1000)
        self.loanSum.setProperty("value", 10000)
        self.loanSum.setObjectName("loanSum")
        self.gridLayout_2.addWidget(self.loanSum, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setStyleSheet("QWidget {\n"
"background:#4fc3f7\n"
"}")
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.mortgageInterestRate = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.mortgageInterestRate.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.mortgageInterestRate.setSingleStep(0.1)
        self.mortgageInterestRate.setProperty("value", 10.0)
        self.mortgageInterestRate.setObjectName("mortgageInterestRate")
        self.gridLayout.addWidget(self.mortgageInterestRate, 1, 0, 1, 1)
        self.mortgagePeriod = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mortgagePeriod.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.mortgagePeriod.setMaximum(999999)
        self.mortgagePeriod.setProperty("value", 10)
        self.mortgagePeriod.setObjectName("mortgagePeriod")
        self.gridLayout.addWidget(self.mortgagePeriod, 2, 0, 1, 1)
        self.mortgageSum = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.mortgageSum.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.mortgageSum.setMaximum(999999999)
        self.mortgageSum.setSingleStep(1000)
        self.mortgageSum.setProperty("value", 10000)
        self.mortgageSum.setObjectName("mortgageSum")
        self.gridLayout.addWidget(self.mortgageSum, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 1, 1, 1)
        self.mortgageCalcButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mortgageCalcButton.sizePolicy().hasHeightForWidth())
        self.mortgageCalcButton.setSizePolicy(sizePolicy)
        self.mortgageCalcButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.mortgageCalcButton.setStyleSheet("QPushButton {\n"
"border-radius: 10px;\n"
"padding: 6px;\n"
"background:#b3e5fc\n"
"}")
        self.mortgageCalcButton.setObjectName("mortgageCalcButton")
        self.gridLayout.addWidget(self.mortgageCalcButton, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 3, 0, 1, 1)
        self.ResultLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ResultLabel.setText("")
        self.ResultLabel.setObjectName("ResultLabel")
        self.gridLayout.addWidget(self.ResultLabel, 6, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit.setStyleSheet("QWidget {\n"
"background:#b3e5fc\n"
"}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(300, 0))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Сумма рассрочки"))
        self.label_9.setText(_translate("MainWindow", "Срок рассрочки (Месяц)"))
        self.installmentsCalcButton.setText(_translate("MainWindow", "Посчитать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Калькулятор рассрочки"))
        self.label_5.setText(_translate("MainWindow", "Срок кредита (Месяц)"))
        self.label_6.setText(_translate("MainWindow", "Сумма кредита"))
        self.label_7.setText(_translate("MainWindow", "Процентная ставка (Месяц)"))
        self.radioButton_3.setText(_translate("MainWindow", "Аннуитетный"))
        self.loanCalcButton.setText(_translate("MainWindow", "Посчитать"))
        self.radioButton_4.setText(_translate("MainWindow", "Дифферинциальный"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Калькулятор кредита"))
        self.label_3.setText(_translate("MainWindow", "Срок ипотеки (Месяц)"))
        self.label.setText(_translate("MainWindow", "Сумма ипотеки"))
        self.label_2.setText(_translate("MainWindow", "Процентная ставка (Месяц)"))
        self.radioButton_2.setText(_translate("MainWindow", "Аннуитетный"))
        self.mortgageCalcButton.setText(_translate("MainWindow", "Посчитать"))
        self.radioButton.setText(_translate("MainWindow", "Дифферинциальный"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Калькулятор ипотеки"))
